import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, useMotionValue, useSpring } from 'motion/react';
import './experience-v2.css';

const projects=[
 {n:'01',name:'CANBOOK',type:'PRODUCT / WEB',year:'2026',url:'https://canbook.vercel.app/',accent:'lime',copy:'Queues, demand, food waste. A canteen system built because waiting in line felt like a problem that should have been solved already.',metric:'ORDER / DEMAND'},
 {n:'02',name:'BRIDGEAI',type:'INDEPENDENT RESEARCH',year:'2026',url:'https://bridge-ai-research--raevn.replit.app/',accent:'blue',copy:'53 participants. Comprehension, confidence, and the question of what happens when dense information gets translated by AI.',metric:'r = .47 / n = 53'},
 {n:'03',name:'TEDxGIIS',type:'CURATION / EVENT',year:'2026',url:'mailto:preshitashinde09@gmail.com?subject=TEDxGIIS%20Abu%20Dhabi%20Youth',accent:'white',copy:'Beyond the Obvious. Speakers, ideas, rooms, people — and the work of making an event feel like more than a schedule.',metric:'SPEAKERS / IDEAS'}
];
const words=['AI','RESEARCH','DESIGN','MUN','TEDx','PRODUCT','QUESTIONS','RABBIT HOLES','BUILDING','PEOPLE','SYSTEMS','STORIES'];

function Clock(){const [t,setT]=useState('');useEffect(()=>{const f=()=>setT(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dubai',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()));f();const i=setInterval(f,1000);return()=>clearInterval(i)},[]);return t}
function Magnetic({children,label='ENTER'}){const ref=useRef(null);const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:360,damping:25}),sy=useSpring(y,{stiffness:360,damping:25});return <motion.div ref={ref} style={{x:sx,y:sy}} onPointerMove={e=>{const r=ref.current?.getBoundingClientRect();if(r){x.set((e.clientX-r.left-r.width/2)*.18);y.set((e.clientY-r.top-r.height/2)*.18)}}} onPointerLeave={()=>{x.set(0);y.set(0)}} data-cursor={label}>{children}</motion.div>}
function DragOrb({label,className}){const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:120,damping:18}),sy=useSpring(y,{stiffness:120,damping:18});return <motion.div className={'drag-orb '+className} style={{x:sx,y:sy}} drag dragMomentum dragElastic={.35} whileDrag={{scale:1.08}} data-cursor="DRAG"><b>{label}</b><span>DRAG</span><i/><i/></motion.div>}
function Field({onCursor}){const ref=useRef(null);useEffect(()=>{const el=ref.current;if(!el)return;const nodes=[...el.querySelectorAll('.field-word')];let raf=0,mx=0,my=0;const move=e=>{mx=e.clientX;my=e.clientY};addEventListener('pointermove',move,{passive:true});const tick=()=>{nodes.forEach((n,i)=>{const r=n.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=cx-mx,dy=cy-my,d=Math.hypot(dx,dy)||1,force=Math.max(0,1-d/240);n.style.transform=`translate(${dx/d*force*28}px,${dy/d*force*28}px) rotate(${(i%4-1.5)*3}deg) scale(${1+force*.14})`});raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);removeEventListener('pointermove',move)}},[]);return <div ref={ref} className="field">{words.map((w,i)=><button className="field-word" key={w} style={{'--i':i}} data-cursor="PULL" onPointerEnter={()=>onCursor('PULL')}>{w}</button>)}</div>}
function App(){const root=useRef(null),canvas=useRef(null),[cursor,setCursor]=useState(''),[index,setIndex]=useState(false),[theme,setTheme]=useState(false),[boot,setBoot]=useState(false),[question,setQuestion]=useState(0),[tele,setTele]=useState({x:0,y:0,v:0,s:0,dir:'↓'});const p=useRef({x:innerWidth/2,y:innerHeight/2,tx:innerWidth/2,ty:innerHeight/2,vx:0,vy:0}),s=useRef({last:scrollY,v:0});
useEffect(()=>{const h=document.documentElement;const move=e=>{p.current.tx=e.clientX;p.current.ty=e.clientY};addEventListener('pointermove',move,{passive:true});let raf,last=performance.now();const loop=now=>{const dt=Math.max(8,now-last);last=now;const q=p.current;q.x+=(q.tx-q.x)*.16;q.y+=(q.ty-q.y)*.16;q.vx=q.vx*.82+(q.tx-q.x)*.18;q.vy=q.vy*.82+(q.ty-q.y)*.18;const v=Math.min(2.8,Math.hypot(q.vx,q.vy)/10);const raw=scrollY-s.current.last;s.current.v=s.current.v*.84+raw*.16;s.current.last=scrollY;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),pct=scrollY/max*100;h.style.setProperty('--mx',q.x+'px');h.style.setProperty('--my',q.y+'px');h.style.setProperty('--mv',v);h.style.setProperty('--ma',Math.atan2(q.vy,q.vx)*57.3+'deg');h.style.setProperty('--sv',Math.min(2.8,Math.abs(s.current.v)/12));h.style.setProperty('--progress',pct+'%');if(now%80<3)setTele({x:Math.round(q.x),y:Math.round(q.y),v:Math.abs(v),s:Math.round(pct),dir:s.current.v<-.2?'↑':'↓'});raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);removeEventListener('pointermove',move)}},[]);
useEffect(()=>{const c=canvas.current,ctx=c.getContext('2d');let W,H,raf;const dots=Array.from({length:90},()=>({x:Math.random(),y:Math.random(),vx:(Math.random()-.5)*.00025,vy:(Math.random()-.5)*.00025,r:.5+Math.random()*1.8}));const resize=()=>{W=innerWidth;H=innerHeight;c.width=W*devicePixelRatio;c.height=H*devicePixelRatio;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)};resize();addEventListener('resize',resize);const draw=()=>{ctx.clearRect(0,0,W,H);const q=p.current;dots.forEach(d=>{let x=d.x*W,y=d.y*H,dx=q.x-x,dy=q.y-y,dist=Math.hypot(dx,dy)||1,f=Math.max(0,1-dist/360);d.x+=d.vx+dx/dist*f*.0006*(1+Number(document.documentElement.style.getPropertyValue('--sv')||0));d.y+=d.vy+dy/dist*f*.0006;if(d.x<0)d.x=1;if(d.x>1)d.x=0;if(d.y<0)d.y=1;if(d.y>1)d.y=0;ctx.globalAlpha=.08+f*.22;ctx.fillStyle=f>.35?'#d7ff32':'#ffffff';ctx.beginPath();ctx.arc(x,y,d.r+f*2,0,Math.PI*2);ctx.fill()});raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize)}},[]);
useEffect(()=>{const id=requestAnimationFrame(()=>setBoot(true));return()=>cancelAnimationFrame(id)},[]);
const go=id=>{setIndex(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
return <main ref={root} className={'experience '+(theme?'theme-alt':'')+' q'+question}>
<canvas ref={canvas} className="particle-canvas"/><div className="noise"/><div className="machine" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i} style={{'--i':i}}/>)}<b>PS</b></div>
<div className="cursor" data-label={cursor}>{cursor&&<span>{cursor}</span>}</div>
<header className="hud"><Magnetic label="HOME"><button onClick={()=>go('home')}>PRESHITA©2026</button></Magnetic><nav><Magnetic><button onClick={()=>go('work')}>WORK</button></Magnetic><Magnetic><button onClick={()=>go('contact')}>CONTACT</button></Magnetic></nav><div><Magnetic label="THEME"><button onClick={()=>setTheme(v=>!v)}>THEME[{theme?'B':'A'}]</button></Magnetic><Magnetic label="INDEX"><button onClick={()=>setIndex(true)}>INDEX[+]</button></Magnetic></div></header>
<aside className="hud-data"><span>GST / ABU DHABI</span><strong><Clock/></strong><span>{String(tele.x).padStart(4,'0')} X {String(tele.y).padStart(4,'0')}</span><span>VEL {tele.v.toFixed(2)}</span><span>SCROLL {tele.s}% {tele.dir}</span></aside><aside className="rail"><span style={{height:tele.s+'%'}}/><b>{tele.dir}</b><small>SCROLL</small></aside>
<section id="home" className="hero scene"><div className="hero-top"><span>01 / 05</span><span>ABU DHABI / UAE</span></div><div className="boot-copy"><small className={boot?'show':''}>STUDENT / BUILDER / RESEARCHER / ORGANISER</small><h1><span>I MAKE</span><span className="serif">THINGS</span><span className="outline">HAPPEN.</span></h1><p className={boot?'show':''}>I build software, research weird questions, design interfaces,<br/>organise things — and follow ideas down rabbit holes.</p></div><div className="hero-coordinate">THE WEBSITE IS WATCHING<br/><em>MOVE YOUR MOUSE.</em></div><DragOrb label="WHY?" className="orb-one"/><DragOrb label="BUILD" className="orb-two"/><button className="scroll-cue" onClick={()=>go('thinking')}>SCROLL TO ENTER <b>↓</b></button></section>
<section id="thinking" className="thinking scene"><div className="section-no">02 / THE RABBIT HOLE</div><div className="thinking-head"><small>THE THING I DO MOST</small><h2>I SEE<br/><span>SOMETHING.</span><br/>THEN I ASK<br/><em>WHY?</em></h2></div><Field onCursor={setCursor}/><button className="question" onClick={()=>setQuestion(v=>(v+1)%3)} data-cursor="CHANGE">?</button><p className="thinking-note">AI / RESEARCH / DESIGN / MUN / TEDx / PRODUCT<br/>PEOPLE / SYSTEMS / STORIES / QUESTIONS</p></section>
<section id="work" className="work scene"><div className="section-no">03 / THINGS THAT ESCAPED THE NOTEBOOK</div><div className="work-title"><small>SELECTED WORLDS</small><h2>MADE<br/><em>REAL.</em></h2></div><div className="project-stack">{projects.map((p,i)=><a className={'project-world '+p.accent} key={p.name} href={p.url} target={p.url.startsWith('http')?'_blank':undefined} rel="noreferrer" data-cursor="OPEN ↗"><div className="project-index">{p.n}<small>/ 03</small></div><div className="project-copy"><div>{p.type} <b>{p.year}</b></div><h3>{p.name}<sup>↗</sup></h3><p>{p.copy}</p><strong>{p.metric}</strong></div><div className="project-visual"><div className="visual-lines"/><div className="visual-core">{i===0?'QUEUE':i===1?'r=.47':'BEYOND'}</div><span>{i===0?'ORDER / DEMAND':i===1?'COMPREHENSION / CONFIDENCE':'SPEAKERS / IDEAS'}</span></div><div className="project-hover">ENTER<br/>WORLD ↗</div></a>)}</div></section>
<section id="now" className="now scene"><div className="section-no">04 / CURRENTLY</div><div className="now-copy"><small>OPEN TABS</small><h2>TOO<br/><em>MANY.</em></h2></div><div className="now-grid">{[['BUILDING','CANBOOK','a school-canteen problem turned into a product.'],['RESEARCHING','BRIDGEAI','AI simplification, comprehension, confidence.'],['CURATING','TEDxGIIS','Beyond the Obvious — speakers, ideas, people.'],['QUESTIONING','NEXT?','probably another rabbit hole.']].map((a,i)=><article key={a[0]} data-cursor="READ"><small>0{i+1} / {a[0]}</small><h3>{a[1]}</h3><p>{a[2]}</p><b>↗</b></article>)}</div><div className="marquee">CURIOUS — BUILDING — RESEARCHING — ORGANISING — QUESTIONING — CURIOUS — BUILDING — RESEARCHING — ORGANISING —</div></section>
<section id="contact" className="contact scene"><div className="section-no">05 / END?</div><div className="contact-center"><small>NOT REALLY.</small><h2>LET'S MAKE<br/><em>SOMETHING<br/>INTERESTING.</em></h2><a href="mailto:preshitashinde09@gmail.com" data-cursor="OPEN ↗">preshitashinde09@gmail.com ↗</a></div><div className="contact-bottom"><span>PS / 2026</span><span>ABU DHABI</span><span>KEEP GOING ↓</span></div></section>
{index&&<div className="index-screen"><button className="index-close" onClick={()=>setIndex(false)}>CLOSE ×</button><div className="index-meta">PRESHITA©2026 <span>LIVE INDEX</span></div><div className="index-list">{[['home','HOME'],['thinking','THINKING'],['work','WORK'],['now','CURRENTLY'],['contact','CONTACT']].map((n,i)=><button key={n[0]} onClick={()=>go(n[0])}><small>0{i+1}</small><span>{n[1]}</span><b>↗</b></button>)}</div><p>MOVE / HOVER / DRAG / SCROLL / QUESTION EVERYTHING</p></div>}
</main>}
createRoot(document.getElementById('root')).render(<App/>);
