const waitForApp=()=>{if(!document.querySelector('.profile'))return setTimeout(waitForApp,40);init()};
function init(){
 const root=document.querySelector('.profile');
 const cursor=document.querySelector('.ambient-cursor');
 let mx=innerWidth/2,my=innerHeight/2,cx=mx,cy=my;
 addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;document.documentElement.style.setProperty('--mx',`${mx}px`);document.documentElement.style.setProperty('--my',`${my}px`)},{passive:true});
 const tick=()=>{cx+=(mx-cx)*.16;cy+=(my-cy)*.16;if(cursor){cursor.style.transform=`translate3d(${cx}px,${cy}px,0)`}requestAnimationFrame(tick)};tick();
 document.querySelectorAll('a,button,.word-space span,.signal,.work-card').forEach(el=>{el.addEventListener('pointerenter',()=>root.classList.add('cursor-active'));el.addEventListener('pointerleave',()=>root.classList.remove('cursor-active'))});
 document.querySelectorAll('[data-float]').forEach(el=>{let down=false,ox=0,oy=0,tx=0,ty=0;el.addEventListener('pointerdown',e=>{down=true;ox=e.clientX-tx;oy=e.clientY-ty;el.setPointerCapture?.(e.pointerId);el.classList.add('dragging')});el.addEventListener('pointermove',e=>{if(!down)return;tx=e.clientX-ox;ty=e.clientY-oy;el.style.setProperty('--drag-x',`${tx}px`);el.style.setProperty('--drag-y',`${ty}px`)});el.addEventListener('pointerup',()=>{down=false;el.classList.remove('dragging')})});
 const overlay=document.createElement('aside');overlay.className='command-menu';overlay.innerHTML=`<button class="menu-close">CLOSE [×]</button><div class="menu-top">PRESHITA©2026 <span>INDEX / LIVE</span></div><div class="menu-links"><button data-go="home">01 / HOME</button><button data-go="thinking">02 / THINKING</button><button data-go="work">03 / WORK</button><button data-go="now">04 / NOW</button><button data-go="contact">05 / CONTACT</button></div><div class="menu-foot">MOVE YOUR CURSOR · DRAG THINGS · SCROLL FOREVER</div>`;document.body.appendChild(overlay);
 const close=()=>overlay.classList.remove('open');overlay.querySelector('.menu-close').onclick=close;overlay.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{close();document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'})});document.querySelector('.tools button:last-child')?.addEventListener('click',()=>overlay.classList.add('open'));
 document.querySelectorAll('.work-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),rx=((e.clientY-r.top)/r.height-.5)*-7,ry=((e.clientX-r.left)/r.width-.5)*7;card.style.setProperty('--rx',`${rx}deg`);card.style.setProperty('--ry',`${ry}deg`)});card.addEventListener('pointerleave',()=>{card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg')})});
 let looping=false;const loop=()=>{if(looping)return;const max=document.documentElement.scrollHeight-innerHeight;if(max<400)return;if(scrollY>max-8){looping=true;scrollTo({top:120,behavior:'instant'});setTimeout(()=>looping=false,80)}else if(scrollY<8){looping=true;scrollTo({top:max-120,behavior:'instant'});setTimeout(()=>looping=false,80)}};addEventListener('scroll',loop,{passive:true});
 const soundBtn=[...document.querySelectorAll('.tools button')].find(b=>b.textContent.includes('SOUND'));let audio=null;const blip=()=>{if(!soundBtn||!soundBtn.textContent.includes('●'))return;audio??=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=220+Math.random()*180;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.07);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.08)};document.querySelectorAll('button,a').forEach(x=>x.addEventListener('click',blip));
}
waitForApp();