import React, { useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, useScroll, useTransform } from 'motion/react';
import { animate, stagger } from 'animejs';
import { gsap } from 'gsap';
import { animated, useSpring } from 'react-spring';
import './experience.css';
import './experience-overrides.css';
import './profile.css';

const PROJECTS = [
  { n:'01', title:'CANBOOK', meta:'PRODUCT / WEB · CANTEEN PRE-ORDER + DEMAND MANAGEMENT', href:'https://canbook.vercel.app/', desc:'A school-canteen product built around a very ordinary problem: queues, uncertain demand, and food prepared without knowing what students actually want.' },
  { n:'02', title:'BRIDGEAI', meta:'AI / INDEPENDENT RESEARCH', href:'https://bridge-ai-research--raevn.replit.app/', desc:'An independent research project exploring whether AI-generated text simplification can improve comprehension and confidence when people work with complex information.' },
  { n:'03', title:'TEDxGIIS', meta:'SPEAKERS + CURATION · ABU DHABI · 2026', href:'mailto:preshitashinde09@gmail.com?subject=TEDxGIIS%20Abu%20Dhabi%20Youth', desc:'Helping build TEDxGIIS Abu Dhabi Youth around Beyond the Obvious — from speaker curation to shaping what happens before the talks reach the stage.' }
];
const FLOWERS=[['10%','18%','72px','11s'],['72%','14%','96px','14s'],['83%','68%','54px','9s'],['18%','74%','120px','16s'],['48%','9%','42px','8s'],['61%','84%','78px','13s'],['91%','34%','38px','10s']];
function Flowers(){return <div className="flower-field" aria-hidden="true">{FLOWERS.map(([x,y,size,speed],i)=><div key={i} className="flower" style={{'--x':x,'--y':y,'--size':size,'--speed':speed}}><i/><b/><span/></div>)}</div>}
function App(){
 const heroRef=useRef(null); const {scrollYProgress}=useScroll(); const orbY=useTransform(scrollYProgress,[0,.35],[0,180]); const [orbSpring]=useSpring({scale:1,config:{mass:1,tension:100,friction:18}});
 useEffect(()=>{const ctx=gsap.context(()=>{gsap.from('.profile-hero .profile-eyebrow',{y:18,opacity:0,duration:.7,ease:'power3.out'});gsap.from('.profile-lede',{y:30,opacity:0,duration:1,delay:.15,ease:'power3.out'});},heroRef);const reveal=animate('.signal, .work-card',{opacity:[0,1],translateY:[28,0]},{delay:stagger(80),duration:800,ease:'out(4)',autoplay:false});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){reveal.play();io.disconnect()}}),{threshold:.12});const target=document.querySelector('.work-section');if(target)io.observe(target);return()=>{ctx.revert();io.disconnect();reveal.pause()}},[]);
 const jump=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}); const magnetic=e=>{const r=e.currentTarget.getBoundingClientRect();gsap.to(e.currentTarget,{x:(e.clientX-(r.left+r.width/2))*.08,y:(e.clientY-(r.top+r.height/2))*.08,duration:.35,ease:'power3.out'})}; const resetMagnetic=e=>gsap.to(e.currentTarget,{x:0,y:0,duration:.5,ease:'elastic.out(1,.45)'});
 return <div className="profile">
  <section id="home" ref={heroRef} className="profile-section profile-hero"><Flowers/><animated.div className="glass-orb" style={orbSpring}><motion.div style={{y:orbY}}/></animated.div><div className="profile-eyebrow">PRESHITA SHINDE · ABU DHABI · 2026</div><h1>HI, I'M<br/><em>PRESHITA.</em></h1><p className="profile-lede">I'm a student who likes <strong>building things, asking questions, and following ideas way further than I probably need to.</strong> Right now, that means AI, research, products, TEDx, MUN, design, and a lot of rabbit holes.</p><button className="profile-scroll" onClick={()=>jump('about')}>SCROLL / THERE'S MORE ↓</button></section>
  <section id="about" className="profile-section profile-about"><div className="profile-grid"><div><div className="profile-eyebrow">A LITTLE CONTEXT</div><h2 className="profile-heading">I LIKE<br/><em>MAKING</em><br/>THINGS.</h2><div className="profile-copy"><p>I usually start with something that bothers me, interests me, or makes me think, <em>“wait — why is it like this?”</em></p><p>Sometimes that becomes a product. Sometimes it becomes research. Sometimes it becomes an event with a room full of people and approximately 700 things to organise.</p><p>I'm not particularly interested in fitting everything into one neat label. I like moving between technology, people, ideas and design — and seeing what happens when they overlap.</p></div></div><motion.div className="profile-note" initial={{rotate:6,y:30,opacity:0}} whileInView={{rotate:2,y:0,opacity:1}} viewport={{once:true}} transition={{duration:.8,ease:[.16,1,.3,1]}}><span>CURRENTLY / OPEN TABS</span><strong>AI.<br/>RESEARCH.<br/>TEDx.<br/><em>MUN.</em></strong><span>+ design, people, stories, fashion, horror, and whatever sends me down another rabbit hole.</span></motion.div></div></section>
  <section id="work" className="profile-section work-section"><div className="work-header"><div><div className="profile-eyebrow">SELECTED WORK</div><h2 className="profile-heading">THINGS I'VE<br/><em>ACTUALLY MADE.</em></h2></div><p>Not a list of everything I've ever touched. Just the things that became real enough to put somewhere on the internet.</p></div><div className="work-list">{PROJECTS.map((p,i)=><motion.a key={p.n} href={p.href} target={i<2?'_blank':undefined} rel={i<2?'noreferrer':undefined} className="work-card" whileHover={{x:10}} transition={{type:'spring',stiffness:260,damping:22}} onMouseMove={magnetic} onMouseLeave={resetMagnetic}><span className="work-number">{p.n}</span><div><h3 className="work-title">{p.title}</h3><div className="work-meta">{p.meta}</div><p style={{maxWidth:620,color:'#aaa',lineHeight:1.5,margin:'18px 0 0'}}>{p.desc}</p></div><span className="work-arrow">↗</span></motion.a>)}</div></section>
  <section id="now" className="profile-section signal-section"><Flowers/><div className="signal-layout"><div className="profile-eyebrow">THE CURRENT TAB</div><h2 className="profile-heading">RIGHT NOW,<br/><em>IT'S A LOT.</em></h2><div className="signal-list"><article className="signal"><small>01 / BUILDING</small><h3>CanBook</h3><p>Turning a school-canteen problem into something students can actually use.</p></article><article className="signal"><small>02 / RESEARCHING</small><h3>BridgeAI</h3><p>Looking at what happens to comprehension and confidence when complex information is simplified with AI.</p></article><article className="signal"><small>03 / ORGANISING</small><h3>TEDxGIIS Abu Dhabi Youth</h3><p>Speaker curation and event-building around <em>Beyond the Obvious.</em></p></article><article className="signal"><small>04 / DOING</small><h3>MUN + everything else</h3><p>Arguing a position, listening to people, designing things, asking better questions, and occasionally getting distracted by a completely new idea.</p></article></div></div></section>
  <section id="contact" className="profile-section contact-section"><div className="profile-eyebrow">YOU MADE IT TO THE END</div><h2 className="contact-heading">LET'S MAKE<br/><em>SOMETHING.</em></h2><a className="contact-link" href="mailto:preshitashinde09@gmail.com" onMouseMove={magnetic} onMouseLeave={resetMagnetic}>preshitashinde09@gmail.com ↗</a><div className="contact-footer"><span>ABU DHABI / UAE</span><a href="https://github.com/raevn45" target="_blank" rel="noreferrer">GITHUB ↗</a><span>PS / 2026</span></div></section>
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
