import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{motion,useMotionValue,useSpring}from'motion/react';
import gsap from'gsap';
import{ScrollTrigger}from'gsap/ScrollTrigger';
import'./universe.css';
gsap.registerPlugin(ScrollTrigger);
const projects=[
{id:'01',name:'CANBOOK',meta:'PRODUCT / WEB / 2026',desc:'A canteen pre-order and demand-management system built around queues, unpredictable demand and food waste.',url:'https://canbook.vercel.app/',kind:'queue'},
{id:'02',name:'BRIDGEAI',meta:'AI / INDEPENDENT RESEARCH / 2026',desc:'An independent study exploring AI-generated text simplification, comprehension and confidence.',url:'https://bridge-ai-research--raevn.replit.app/',kind:'data'},
{id:'03',name:'TEDxGIIS',meta:'CURATION / EVENT / 2026',desc:'Building TEDxGIIS Abu Dhabi Youth around Beyond the Obvious — ideas, speakers and people.',url:'mailto:preshitashinde09@gmail.com?subject=TEDxGIIS%20Abu%20Dhabi%20Youth',kind:'event'}];
const words=['AI','RESEARCH','DESIGN','MUN','TEDx','PRODUCT','QUESTIONS','RABBIT HOLES','BUILDING','PEOPLE','SYSTEMS','STORIES'];
function Clock(){const[t,setT]=useState('');useEffect(()=>{const f=()=>setT(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dubai',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()));f();const i=setInterval(f,1000);return()=>clearInterval(i)},[]);return t}
function DragThing({label,kind,x,y,setCursor}){const X=useMotionValue(x),Y=useMotionValue(y),sx=useSpring(X,{stiffness:170,damping:20}),sy=useSpring(Y,{stiffness:170,damping:20});return <motion.button className={'drag-thing '+kind} style={{x:sx,y:sy}} drag dragMomentum dragElastic={.2} whileDrag={{scale:1.1,rotate:-5}} onPointerEnter={()=>setCursor('DRAG')} onPointerLeave={()=>setCursor('')}><b>{label}</b><i/><i/><i/><small>DRAG ME</small></motion.button>}
function App(){
const root=useRef(null),cursor=useRef(null),canvas=useRef(null),p=useRef({x:innerWidth/2,y:innerHeight/2,px:innerWidth/2,py:innerHeight/2,vx:0,vy:0}),sc=useRef({y:scrollY,v:0}),[cursorState,setCursor]=useState(''),[index,setIndex]=useState(false),[theme,setTheme]=useState(false),[sound,setSound]=useState(false),[question,setQuestion]=useState(0),[active,setActive]=useState(null),[telemetry,setTelemetry]=useState({x:0,y:0,v:0,s:0,d:'↓'}),audio=useRef(null);
useEffect(()=>{const e=document.documentElement,move=a=>{p.current.x=a.clientX;p.current.y=a.clientY;e.style.setProperty('--mx',a.clientX+'px');e.style.setProperty('--my',a.clientY+'px')};addEventListener('pointermove',move,{passive:true});let raf,last=performance.now();const loop=now=>{const dt=Math.max(8,now-last);last=now;const q=p.current;q.vx=q.vx*.8+(q.x-q.px)*(60/dt)*.2;q.vy=q.vy*.8+(q.y-q.py)*(60/dt)*.2;q.px=q.x;q.py=q.y;const v=Math.min(3,Math.hypot(q.vx,q.vy)/24),a=Math.atan2(q.vy,q.vx)*57.3;const raw=scrollY-sc.current.y;sc.current.v=sc.current.v*.82+raw*.18;sc.current.y=scrollY;const sv=Math.min(3,Math.abs(sc.current.v)/18),max=Math.max(1,document.documentElement.scrollHeight-innerHeight),pct=scrollY/max*100;e.style.setProperty('--pv',v);e.style.setProperty('--pa',a+'deg');e.style.setProperty('--sv',sv);e.style.setProperty('--sa',scrollY*.045+'deg');e.style.setProperty('--progress',pct+'%');if(cursor.current){const ox=+(cursor.current.dataset.x||q.x),oy=+(cursor.current.dataset.y||q.y),nx=ox+(q.x-ox)*.24,ny=oy+(q.y-oy)*.24;cursor.current.dataset.x=nx;cursor.current.dataset.y=ny;cursor.current.style.transform=`translate3d(${nx}px,${ny}px,0) translate(-50%,-50%) rotate(${a}deg) scale(${1+v*.28},${1-Math.min(.18,v*.04)})`}if(now%70<3)setTelemetry({x:Math.round(q.x),y:Math.round(q.y+scrollY),v:Math.abs(sc.current.v),s:pct,d:sc.current.v<-.3?'↑':'↓'});raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);removeEventListener('pointermove',move)}},[]);
useEffect(()=>{const c=canvas.current,x=c.getContext('2d'),dots=[];let raf;const size=()=>{c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)};size();addEventListener('resize',size);for(let i=0;i<75;i++)dots.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.4+Math.random()*1.5,v:.2+Math.random()*.5,a:Math.random()*6.28});const draw=()=>{x.clearRect(0,0,innerWidth,innerHeight);const q=p.current;for(const d of dots){const dx=q.x-d.x,dy=q.y-d.y,dist=Math.hypot(dx,dy)||1,f=Math.max(0,1-dist/260);d.x+=Math.cos(d.a)*d.v+dx/dist*f*.5;d.y+=Math.sin(d.a)*d.v+dy/dist*f*.5-Math.abs(sc.current.v)*.12;if(d.x<-10)d.x=innerWidth+10;if(d.x>innerWidth+10)d.x=-10;if(d.y<-10)d.y=innerHeight+10;if(d.y>innerHeight+10)d.y=-10;x.globalAlpha=.1+f*.3;x.fillStyle='#d2ff25';x.beginPath();x.arc(d.x,d.y,d.r+f,0,6.28);x.fill()}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',size)}},[]);
useEffect(()=>{const ctx=gsap.context(()=>{gsap.utils.toArray('.reveal').forEach((el,i)=>gsap.fromTo(el,{y:80,opacity:0},{y:0,opacity:1,duration:1,delay:i*.02,ease:'expo.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));gsap.to('.machine',{rotation:360,ease:'none',scrollTrigger:{trigger:'#home',start:'top top',end:'bottom top',scrub:2}});gsap.to('.botanical',{rotation:32,scale:1.16,ease:'none',scrollTrigger:{trigger:root.current,start:'top top',end:'bottom bottom',scrub:2}})},root);return()=>ctx.revert()},[]);
useEffect(()=>{const el=root.current,over=e=>{const t=e.target.closest('[data-cursor]');if(t)setCursor(t.dataset.cursor)},out=e=>{if(e.target.closest('[data-cursor]'))setCursor('')};el.addEventListener('pointerover',over);el.addEventListener('pointerout',out);return()=>{el.removeEventListener('pointerover',over);el.removeEventListener('pointerout',out)}},[]);
const go=id=>{setIndex(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
const blip=()=>{if(!sound)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio.current??=new AC();const o=audio.current.createOscillator(),g=audio.current.createGain();o.frequency.value=280+Math.random()*300;g.gain.setValueAtTime(.012,audio.current.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.current.currentTime+.07);o.connect(g);g.connect(audio.current.destination);o.start();o.stop(audio.current.currentTime+.07)};
return <main ref={root} className={'universe '+(theme?'alt':'')+' q'+question} onClick={blip}><canvas ref={canvas} className="particles"/><div className="grain"/><div className="kaleido">{Array.from({length:18},(_,i)=><i key={i} style={{'--i':i}}/>)}</div><div className="botanical"><span>✿</span><span>❀</span><span>✾</span><span>✽</span></div><div ref={cursor} className={'cursor '+(cursorState?'label':'')} data-x="0" data-y="0"><span>{cursorState||'·'}</span></div>
<header className="hud"><button data-cursor="ENTER" onClick={()=>go('home')}>✳ PRESHITA©2026</button><nav><button data-cursor="ENTER" onClick={()=>go('work')}>WORK</button><button data-cursor="ENTER" onClick={()=>go('contact')}>CONTACT</button></nav><div><button data-cursor="THEME" onClick={()=>setTheme(v=>!v)}>THEME[{theme?'B':'A'}]</button><button data-cursor="SOUND" onClick={()=>setSound(v=>!v)}>SOUND[{sound?'●':'|'}]</button><button data-cursor="INDEX" onClick={()=>setIndex(true)}>INDEX[+]</button></div></header>
<aside className="telemetry"><span>GST / ABU DHABI</span><strong><Clock/></strong><span>{String(telemetry.x).padStart(4,'0')} X {String(telemetry.y).padStart(4,'0')} Y</span><span>VEL {telemetry.v.toFixed(2)}</span><span>SCROLL {telemetry.s.toFixed(0)}% {telemetry.d}</span></aside><aside className="rail"><i/><b>↗</b><small>SCROLL</small></aside>
<section id="home" className="scene hero"><small className="meta">01 / ∞<br/>ABU DHABI / UAE<br/>STUDENT · BUILDER · RESEARCHER</small><div className="hero-copy"><small>INITIALISING / PRESHITA.OS</small><h1><span>I MAKE</span><em>THINGS</em><strong>HAPPEN.</strong></h1><p>I build software, research strange questions, organise things,<br/>and occasionally follow an idea until it becomes a real thing.</p></div><div className="machine"><div/><div/><div/><b>?</b><small>MOUSE / SCROLL / DRAG</small></div><DragThing label="CURIOUS" kind="lime" x={innerWidth*.66} y={innerHeight*.68} setCursor={setCursor}/><DragThing label="ALWAYS" kind="blue" x={innerWidth*.78} y={innerHeight*.32} setCursor={setCursor}/><button className="continue" data-cursor="DOWN" onClick={()=>go('thinking')}>KEEP GOING ↓</button></section>
<section id="thinking" className="scene thinking"><small className="meta">02 / ∞<br/>THE RABBIT HOLE</small><div className="think-layout"><div className="think-copy reveal"><small>WHY?</small><h2>I SEE<br/><em>SOMETHING.</em><br/>THEN I ASK<br/><span>WHY?</span></h2><p>Usually the answer is: <em>okay, but why does it have to work like that?</em><br/><br/>Sometimes that becomes a product. Sometimes research. Sometimes an event. Sometimes twelve open tabs and a completely different project.</p></div><div className="word-field">{words.map((w,i)=><button data-cursor="PULL" key={w} style={{'--i':i}}>{w}</button>)}</div></div><button className="question" data-cursor="CHANGE" onClick={()=>setQuestion(v=>(v+1)%3)}>?</button></section>
<section id="work" className="scene work"><small className="meta">03 / ∞<br/>SELECTED WORLDS</small><div className="work-title reveal"><small>THINGS THAT ESCAPED THE NOTEBOOK</small><h2>I <em>MADE</em> THEM.</h2></div><div className="worlds">{projects.map(p=><a key={p.id} href={p.url} target={p.url.startsWith('http')?'_blank':undefined} rel="noreferrer" data-cursor="OPEN ↗" className={'world '+p.kind+(active===p.id?' active':'')} onPointerEnter={()=>setActive(p.id)} onPointerLeave={()=>setActive(null)}><small className="world-id">{p.id}<br/>/∞</small><div className="world-copy"><small>{p.meta}</small><h3>{p.name}<b>↗</b></h3><p>{p.desc}</p><strong>ENTER WORLD</strong></div><div className="world-art"><div className="grid"/><div className="core">{p.kind==='queue'?'QUEUE':p.kind==='data'?'r=.47':'BEYOND'}</div><div className="orbit"/><small>{p.kind==='queue'?'ORDER / DEMAND':p.kind==='data'?'COMPREHENSION / CONFIDENCE':'SPEAKERS / IDEAS'}</small></div><div className="ghost">{p.name}</div></a>)}</div></section>
<section id="now" className="scene now"><small className="meta">04 / ∞<br/>CURRENTLY / OPEN TABS</small><div className="now-title reveal"><small>RIGHT NOW</small><h2>IT'S<br/><em>A LOT.</em></h2></div><div className="signals">{[['BUILDING','CanBook','A school-canteen problem turned into a product.'],['RESEARCHING','BridgeAI','AI simplification, comprehension and confidence.'],['CURATING','TEDxGIIS Abu Dhabi Youth','Speaker curation around Beyond the Obvious.'],['QUESTIONING','Whatever is next','MUN, design, people, stories, rabbit holes.']].map((a,i)=><article className="signal reveal" data-cursor="READ" key={a[0]}><small>0{i+1} / {a[0]}</small><h3>{a[1]}</h3><p>{a[2]}</p><span>↗</span></article>)}</div><div className="marquee">CURIOUS · BUILDING · RESEARCHING · ORGANISING · QUESTIONING · CURIOUS · BUILDING · RESEARCHING · ORGANISING · QUESTIONING ·</div></section>
<section id="contact" className="scene contact"><small className="meta">05 / ∞<br/>END? NOT REALLY.</small><small>END? NOT REALLY.</small><h2 className="reveal">LET'S MAKE<br/><em>SOMETHING<br/>INTERESTING.</em></h2><a data-cursor="OPEN ↗" className="email" href="mailto:preshitashinde09@gmail.com">preshitashinde09@gmail.com ↗</a><div className="footer"><span>ABU DHABI / UAE</span><a data-cursor="OPEN ↗" href="https://github.com/raevn45" target="_blank" rel="noreferrer">GITHUB ↗</a><span>PS / 2026</span></div></section>
{index&&<div className="index"><button data-cursor="CLOSE" onClick={()=>setIndex(false)}>CLOSE [×]</button><div className="index-top">PRESHITA©2026 <span>INDEX / LIVE</span></div><div className="index-links">{[['home','HOME'],['thinking','THINKING'],['work','WORK'],['now','CURRENTLY'],['contact','CONTACT']].map((n,i)=><button data-cursor="ENTER" key={n[0]} onClick={()=>go(n[0])}><small>0{i+1}</small>{n[1]}<b>↗</b></button>)}</div><p>MOVE · HOVER · DRAG · SCROLL · CLICK THE ? · KEEP GOING</p></div>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
